### ISSUE TITLE
Installation not working

### ISSUE THREAD

**Issue by mhammerschmidt** [otherguy/laravel-error-handler#3]
Hi,
I have installed your package after your instructions.
When i throw an error to see if it is working the page isn't loading.

Errorlog:
[Tue Jan 24 17:49:43.525348 2017] [proxy_fcgi:error] [pid 1433] [client 10.4.2.152:44838] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Illuminate\\Foundation\\Exceptions\\Handler::__construct() must implement interface Psr\\Log\\LoggerInterface, instance of Illuminate\\Foundation\\Application given, called in /home/mht/workspace/example/vendor/winternight/laravel-error-handler/src/Handlers/ExceptionHandler.php on line 60 and defined in /home/mht/workspace/example/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php:43\nStack trace:\n#0 /home/mht/workspace/example/vendor/winternight/laravel-error-handler/src/Handlers/ExceptionHandler.php(60): Illuminate\\Foundation\\Exceptions\\Handler->__construct(Object(Illuminate\\Foundation\\Application))\n#1 [internal function]: Winternight\\LaravelErrorHandler\\Handlers\\ExceptionHandler->__construct(Object(Illuminate\\Foundation\\Application))\n#2 /home/mht/workspace/example/vendor/laravel/framework/src/Illuminate/Container/Container.php(779): ReflectionClass->newInstanceArgs(Array)\n#3 /home/mht/workspace/example/vendor/laravel/framework/src/Illum...\nPHP message: PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Illuminate\\Foundation\\Exceptions\\Handler::__construct() must implement interface Psr\\Log\\LoggerInterface, instance of Illuminate\\Foundation\\Application given, called in /home/mht/workspace/example/vendor/winternight/laravel-error-handler/src/Handlers/ExceptionHandler.php on line 60 and defined in /home/mht/workspace/example/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php:43\nStack trace:\n#0 /home/mht/workspace/example/vendor/winternight/laravel-error-handler/src/Handlers/ExceptionHandler.php(60): Illuminate\\Foundation\\Exceptions\\Handler->__construct(Object(Illuminate\\Foundation\\Application))\n#1 [internal function]: Winternight\\LaravelErrorHandler\\Handlers\\ExceptionHandler->__construct(Object(Illuminate\\Foundation\\Application))\n#2 /home/mht/workspace/example/vendor/laravel/framework/src/Illuminate/Container/Container.php(779): ReflectionClass->newInstanceArgs(Array)\n#3 /home/mht/workspace/example/vendor/laravel/framework/src/Illum...\n'

**Comment by darkwinternight** [comment]
Thanks for the report! Do you have any further details?

**Comment by mhammerschmidt** [comment]
In winternight/laravel-error-handler/src/Handlers/ExceptionHandler.php on line 60.
The $container array got a sub array instance in which is the same instance array over and over again.
After the timelimit is reached the 500 browser error is shown

**Comment by darkwinternight** [comment]
Thanks! I will look into it.

**Comment by mash1t** [comment]
@mhammerschmidt After updating from Laravel 5.2.* to 5.3.* it works again.

**Comment by otherguy** [comment]
Closing this as it's no longer relevant.
